name: Build

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    env:
        PATH: ".\\"
        BUILD_METHOD_WIN64: "BuildProject.BuildWindows64"
        BUILD_METHOD_WIN32: "BuildProject.BuildWindows32"
        gameName: "Haste"
        projectVersion: 
    steps:
      - uses: actions/checkout@v2
      - name: Build For Windows 64 bits
        run: |
          $env:projectVersion = "0.1.$env:GITHUB_RUN_ID"
          Start-Process -Wait 'C:\Program Files\Unity\Hub\Editor\2020.3.12f1\Editor\Unity.exe' -ArgumentList "-nographics -batchmode -projectPath $env:PATH -executeMethod $env:BUILD_METHOD_WIN64 -quit"
      - name: Build For Windows 32 bits
        run: |
          $env:projectVersion = "0.1.$env:GITHUB_RUN_ID"
          Start-Process -Wait 'C:\Program Files\Unity\Hub\Editor\2020.3.12f1\Editor\Unity.exe' -ArgumentList "-nographics -batchmode -projectPath $env:PATH -executeMethod $env:BUILD_METHOD_WIN32 -quit"
      - uses: actions/upload-artifact@v2
        with:
          name: executable
          path: Builds/*
